# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='post',
        ),
    ]
